import 'package:flutter/material.dart';
import 'package:pluto_grid/pluto_grid.dart';

class Columns {
  static List<PlutoColumn> importsColumns = [
    PlutoColumn(
      title: "التاجر",
      field: 'customer',
      // instead of 'price3'
      type: PlutoColumnType.text(),
      enableFilterMenuItem: false,
      enableColumnDrag: false,
      enableContextMenu: false,
      enableAutoEditing: false,
      enableDropToResize: false,
      enableHideColumnMenuItem: false,
      enableSetColumnsMenuItem: false,
      enableSorting: false,

      enableRowDrag: false,
      enableRowChecked: false,
      filterPadding: EdgeInsets.zero,
      titleTextAlign: PlutoColumnTextAlign.center,
    ),
    PlutoColumn(
      title: "الصنف",
      field: 'fruit',
      // instead of 'type'
      type: PlutoColumnType.text(),
      enableFilterMenuItem: false,
      enableColumnDrag: false,
      enableContextMenu: false,
      enableAutoEditing: false,
      enableDropToResize: false,
      enableHideColumnMenuItem: false,
      enableSetColumnsMenuItem: false,
      enableSorting: false,

      enableRowDrag: false,
      enableRowChecked: false,
      filterPadding: EdgeInsets.zero,
      titlePadding: EdgeInsets.zero,
      titleTextAlign: PlutoColumnTextAlign.center,
    ),
    PlutoColumn(
      title: "السعر",
      field: 'price',
      type: PlutoColumnType.number(),
      textAlign: PlutoColumnTextAlign.center,
      enableFilterMenuItem: false,
      enableColumnDrag: false,
      enableContextMenu: false,
      enableAutoEditing: false,
      enableDropToResize: false,
      enableHideColumnMenuItem: false,
      enableSetColumnsMenuItem: false,
      enableSorting: false,

      enableRowDrag: false,
      filterPadding: EdgeInsets.zero,
      titleTextAlign: PlutoColumnTextAlign.center,
    ),
    PlutoColumn(
      title: "الوزن",
      field: 'weight',
      type: PlutoColumnType.number(),
      textAlign: PlutoColumnTextAlign.center,
      enableFilterMenuItem: false,
      enableColumnDrag: false,
      enableContextMenu: false,
      enableAutoEditing: false,
      enableDropToResize: false,
      enableHideColumnMenuItem: false,
      enableSetColumnsMenuItem: false,
      enableSorting: false,

      enableRowDrag: false,
      enableRowChecked: false,
      filterPadding: EdgeInsets.zero,
      titleTextAlign: PlutoColumnTextAlign.center,
    ),
    PlutoColumn(
      title: "العدد",
      field: 'count',
      type: PlutoColumnType.number(),
      textAlign: PlutoColumnTextAlign.center,
      enableFilterMenuItem: false,
      enableColumnDrag: false,
      enableContextMenu: false,
      enableAutoEditing: false,
      enableDropToResize: false,
      enableHideColumnMenuItem: false,
      enableSetColumnsMenuItem: false,
      enableSorting: false,

      enableRowDrag: false,
      enableRowChecked: false,
      filterPadding: EdgeInsets.zero,
      titleTextAlign: PlutoColumnTextAlign.center,
    ),

    PlutoColumn(
      title: "الاجمالي",
      field: 'total',
      type: PlutoColumnType.number(),
      textAlign: PlutoColumnTextAlign.center,
      enableFilterMenuItem: false,
      enableColumnDrag: false,
      enableContextMenu: false,
      enableAutoEditing: false,
      enableDropToResize: false,
      enableHideColumnMenuItem: false,
      enableSetColumnsMenuItem: false,
      enableSorting: false,

      enableRowDrag: false,
      enableRowChecked: false,
      filterPadding: EdgeInsets.zero,
      titleTextAlign: PlutoColumnTextAlign.center,
    ),
  ];

  static List<PlutoColumn> purchasesColumns = [
    PlutoColumn(
      title: "السعر",
      field: 'price',
      type: PlutoColumnType.number(),
      textAlign: PlutoColumnTextAlign.center,
      enableFilterMenuItem: false,
      enableColumnDrag: false,
      enableContextMenu: false,
      enableAutoEditing: false,
      enableDropToResize: false,
      enableHideColumnMenuItem: false,
      enableSetColumnsMenuItem: false,
      enableSorting: false,
      enableRowDrag: false,
      enableRowChecked: false,
      filterPadding: EdgeInsets.zero,
      titleTextAlign: PlutoColumnTextAlign.center,
    ),
    PlutoColumn(
      title: "الصنف",
      field: 'type',
      type: PlutoColumnType.text(),
      textAlign: PlutoColumnTextAlign.center,
      enableFilterMenuItem: false,
      enableColumnDrag: false,
      enableContextMenu: false,
      enableAutoEditing: false,
      enableDropToResize: false,
      enableHideColumnMenuItem: false,
      enableSetColumnsMenuItem: false,
      enableSorting: false,
      enableRowDrag: false,
      enableRowChecked: false,
      filterPadding: EdgeInsets.zero,
      titleTextAlign: PlutoColumnTextAlign.center,
    ),
    PlutoColumn(
      title: "الوزن",
      field: 'price1',
      type: PlutoColumnType.number(),
      textAlign: PlutoColumnTextAlign.center,
      enableFilterMenuItem: false,
      enableColumnDrag: false,
      enableContextMenu: false,
      enableAutoEditing: false,
      enableDropToResize: false,
      enableHideColumnMenuItem: false,
      enableSetColumnsMenuItem: false,
      enableSorting: false,
      enableRowDrag: false,
      enableRowChecked: false,
      filterPadding: EdgeInsets.zero,
      titleTextAlign: PlutoColumnTextAlign.center,
    ),
    PlutoColumn(
      title: "العدد",
      field: 'price2',
      type: PlutoColumnType.number(),
      textAlign: PlutoColumnTextAlign.center,
      enableFilterMenuItem: false,
      enableColumnDrag: false,
      enableContextMenu: false,
      enableAutoEditing: false,
      enableDropToResize: false,
      enableHideColumnMenuItem: false,
      enableSetColumnsMenuItem: false,
      enableSorting: false,
      enableRowDrag: false,
      enableRowChecked: false,
      filterPadding: EdgeInsets.zero,
      titleTextAlign: PlutoColumnTextAlign.center,
    ),

    PlutoColumn(
      title: "الاجمالي",
      field: 'price4',
      type: PlutoColumnType.number(),
      textAlign: PlutoColumnTextAlign.center,
      enableFilterMenuItem: false,
      enableColumnDrag: false,
      enableContextMenu: false,
      enableAutoEditing: false,
      enableDropToResize: false,
      enableHideColumnMenuItem: false,
      enableSetColumnsMenuItem: false,
      enableSorting: false,
      enableRowDrag: false,
      enableRowChecked: false,
      filterPadding: EdgeInsets.zero,
      titleTextAlign: PlutoColumnTextAlign.center,
    ),
  ];
}
